//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dibware.StoredProcedureFramework.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dibware.StoredProcedureFramework.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading from stargetObjectored storedProcedure &apos;{0}&apos; :  &apos;{1}&apos;.
        /// </summary>
        public static string ErrorReadingStoredProcedure {
            get {
                return ResourceManager.GetString("ErrorReadingStoredProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected type was {0}, actual type was {1}. .
        /// </summary>
        public static string ParameterInvalidTypeFormat {
            get {
                return ResourceManager.GetString("ParameterInvalidTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected length was {0}, actual length was {1}. .
        /// </summary>
        public static string ParameterLengthOutOfRangeFormat {
            get {
                return ResourceManager.GetString("ParameterLengthOutOfRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected precision should be {0}, but actual was {2}. Expected Scales was {1}, but actual was {3}..
        /// </summary>
        public static string ParameterPrecisionAndScaleOutOfRangeFormat {
            get {
                return ResourceManager.GetString("ParameterPrecisionAndScaleOutOfRangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored storedProcedure does not havea name set!.
        /// </summary>
        public static string StoredProcedureDoesNotHaveName {
            get {
                return ResourceManager.GetString("StoredProcedureDoesNotHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stored storedProcedure is not fully constructed! Ensure storedProcedure has name and return type. .
        /// </summary>
        public static string StoredProcedureIsNotFullyConstructed {
            get {
                return ResourceManager.GetString("StoredProcedureIsNotFullyConstructed", resourceCulture);
            }
        }
    }
}
