CREATE PROCEDURE [app].[AllCommonDataTypes]
    @BigInt             bigint
,   @Binary             binary
,   @Bit                bit
,   @Char               char
,   @Date               date
,   @DateTime           datetime
,   @DateTime2          datetime2
,   @Decimal            decimal
,   @float              float
,   @image              image
,   @Int                int
,   @Money              money
,   @NChar              nchar
,   @NText              ntext
,   @Numeric            numeric
,   @NVarchar           nvarchar
,   @Real               real
,   @Smalldatetime      smalldatetime
,   @Smallint           smallint
,   @Smallmoney         smallmoney
,   @Text               text
,   @Time               time
,   @Timestamp          timestamp
,   @Tinyint            tinyint
,   @Uniqueidentifier   uniqueidentifier
,   @Varbinary          varbinary
,   @Varchar            varchar
,   @Xml                xml
AS
    SELECT 
        @BigInt         [BigInt]
,       @Binary         [Binary]
,       @Bit            [Bit]
,       @Char           /*[Char]*/
,       @Date           [Date]
,       @DateTime       [DateTime]
,       @DateTime2      [DateTime2]
,       @Decimal        [Decimal]
,       @float          [Float]
,       @image          [Image]
,       @Int            [int]
,       @Money          [Money]
,       @NChar          [NChar]
,       @NText          [NText]
,       @Numeric        [Numeric]
,       @NVarchar       [NVarchar]
,       @Real           [Real]
,       @Smalldatetime  [SmallDateTime]
,       @Smallint       [SmallInt]
,       @Smallmoney     [SmallMoney]
,       @Text           [Text]
,       @Time           [Time]
,       @Timestamp      [TimeStamp]
,       @Tinyint            [TinyInt]
,       @Uniqueidentifier   [UniqueIdentifier]
,       @Varbinary          [VarBinary]
,       @Varchar            [VarChar]
,       @Xml                [Xml]
RETURN 0
